### ISSUE TITLE
Does not work with latest moment-timezone

### ISSUE THREAD

**Issue by jason-krypton** [andruhon/moment-weekday-calc#17]
The `moment-weekday-calc` methods no longer properly attach to `moment-timezone` when upgrading to `0.5.14`

You can still access them if you import `moment` directly but doing so causes all sorts of timezone conversion issues.

**Comment by andruhon** [comment]
Hi! Could you please provide an example of failing code (with dependencies list)?

**Comment by jason-krypton** [comment]
Sorry about the delay :)

I dug more into this and it looks like I was thrown off by a yarn bug https://github.com/yarnpkg/yarn/issues/3967 which was creating two instances of moment. This caused moment-weekday-calc to attach to the wrong instance of moment.

Which brings me to a different point, while modifying globals in javascript seems fairly par for the course it does not seem like a great practice. It would be awesome if moment-weekday-calc instead exposed an api directly.

Thanks!

**Comment by andruhon** [comment]
@jason-krypton as far as I remember it exports `WeekDayCalc`, I'll have a look, thanks

**Comment by macrozone** [comment]
similar problem on react-native where i need to import `import moment from 'moment/min/moment-with-locales'`

is there a static method which can be applied to moment to attach this functionallity?
