### ISSUE TITLE
How to get a list of days in an array ?

### ISSUE THREAD

**Issue by chanakaDe** [andruhon/moment-weekday-calc#18]
Guys,

This is my code : 

> var demo1 = moment().weekdayCalc({
            rangeStart: '2018-12-01',
            rangeEnd: '2018-12-31',
            weekdays: [ 2],
            exclusions: ['2018-12-11', '2018-12-26']
        });
        console.log("COUNT : ", demo1);

Now from this code, I only get a number. Result is 3. 
I want to get that 3 days in an array.
Like this : ['xxxx-xx-xx','xxxx-xx-xx','xxxx-xx-xx']
Because I need to save them in database.
Please help me and tell me how to take that.
@andruhon :+1:

**Comment by andruhon** [comment]
Sorry, @chanakaDe , this is currently out of the scope of this plugin. You can always contribute if you would like.

**Comment by chanakaDe** [comment]
@andruhon It's ok buddy. These days I'm trying to get a dates list. It's working for 1 month. But when I'm requesting date list of 2 months, count is correct. But the date list is wrong. Only showing start date and end date.
I'm still trying to get that work. It's so important to get date list as well as dates count.
If you have any clue about this issue, let me know please.
Anyway this is a great plugin. :+1:

**Comment by chanakaDe** [comment]
@andruhon I managed to get a list. Only for 1 month. When the range is exceeding 1 month, count is valid but the list is invalid. 

```
WeekDayCalc.prototype.calculateIterative = function(rangeStart,rangeEnd,weekdays,exclusions, inclusions) {
    var weekDaysCount = 0, day = rangeStart.clone();
    var str_exclusions = parseSet(exclusions);
    var str_inclusions = parseSet(inclusions);

    while(day.valueOf()<=rangeEnd.valueOf()) {
      var weekdayFunc = this.useIsoWeekday?'isoWeekday':'weekday';
      var dayString = day.format("YYYY-MM-DD");
      var included = str_inclusions.length != 0 && str_inclusions.indexOf(dayString)>=0;
      if (included || ( (weekdays.indexOf(day[weekdayFunc]())>=0) && (str_exclusions.length==0 || str_exclusions.indexOf(dayString)<0) )) {
        console.log("output : ",dayString);
        week_day_array.push(dayString);
        weekDaysCount++;
      }
      day.add(1, 'day');
    }
    return weekDaysCount;
  };
```

This is all I'm doing.. 
`week_day_array.push(dayString);`
Pushing `dayString` to an array. 
What's going on here when adding 2 months or more than 1 month ?
I'm not troubling you. Is there any specific place you are calculating if the range is more than 1 month ?
Just 1 question and I will continue and i will manage and keep using of this repository. This is so useful to me.

**Comment by andruhon** [comment]
Hi @chanakaDe ! Could you please give me arguments you passing into changed function and which exactly results you expect expect.

**Comment by chanakaDe** [comment]
@andruhon These are the arguments I'm passing 
```
var demo1 = moment().weekdayCalc({
            rangeStart: '2019-01-01',
            rangeEnd: '2019-02-28',
            weekdays: [0,1, 2, 3, 4, 5,6]
        });
        console.log("COUNT : ", demo1[0]);
        console.log("DATES : ", demo1[1]);
```

And this is the output I'm getting : 

![screenshot from 2019-01-21 14-47-26](https://user-images.githubusercontent.com/7803591/51464432-8de89380-1d8b-11e9-8f66-b053f6510ac5.png)

**Comment by chanakaDe** [comment]
@andruhon 
thank you so much for helping me.
Simply what I want is, if there are 59 dates between my date range, I need 59 date elements in my dates array. Those are the loan payment dates in my Loan Management System.

When I'm selecting the date range bigger than 1 month, always date array is not accurate. You can see 2 screenshots in my previous comments. 

If you can help me, i'm so grateful to you and i will contribute and maintain this repository. This whole plugin is so useful to me and my system. 

Thank you so much again. Waiting for your response my friend. :+1:

**Comment by chanakaDe** [comment]
@andruhon I came home just now and testing the code you shared with me brother.
Thank you so much for the effort. :+1: 
You are helpful.

**Comment by chanakaDe** [comment]
@andruhon  yeah this is ok. Can you please make a new release ?
And you bare based in New Zealand. No ? 
I sent you an email. About a job information. :+1:

**Comment by chanakaDe** [comment]
@andruhon 
I figured out now. 
Sometimes it's going out.
When  I select 2019-01-01 as the start date, in the list , I can see 2018-12-31 as the start date.

**Comment by andruhon** [comment]
Published a new release.
