### ISSUE TITLE
Implement exceptions API usage

### ISSUE THREAD

**Issue by MaxPovver** [andruhon/moment-weekday-calc#3]
Your project would be times more usefull if it'd load exception by itsef. I recommend you basicdata.ru/api/json/calend for that(format description is here: basicdata.ru/api/calend ). It's better to implement it in such way that it'd be replaceable with any another api.(the best way here is function that takes api url and returns it's data in standart format for your program)

**Comment by andruhon** [comment]
There's also a question about Mondayised/Fridayised public holidays if they fall fall on a Saturday or Sunday (or whatever the weekend is). I think it should be a separate module decoupled from the app calculating weekdays (passing these results into weekday calc). It would be nice to hear any suggestions from moment-weekday-calc users

**Comment by andruhon** [comment]
Partially addressed by #5
