### ISSUE TITLE
Examples fail with "weekdays must be defined"

### ISSUE THREAD

**Issue by adam-lynch** [andruhon/moment-weekday-calc#4]

**Comment by andruhon** [comment]
Hi Adam! Please confirm that the issue with "node standalone" is one you reported.

**Comment by adam-lynch** [comment]
Sorry, I mean running the examples from the readme don't work.

**Comment by andruhon** [comment]
Could you please clarify which one?

**Comment by adam-lynch** [comment]
It was more than one. I'm pretty sure one of them was the first one (except with different dates);

```javascript
moment().weekdayCalc('16 Sept 2015','16 Oct 2015',[0,1,2,3,4,5,6]); 
```

I think I ran this one too (different dates again):

```javascript
moment().weekdayCalc({  
  rangeStart: '16 Seot 2015',  
  rangeEnd: '16 Oct 2015',  
  weekdays: [1,2,3,4,5]  
  // exclusions: ['6 Apr 2015','7 Apr 2015']  // I commented this bit out I think
}) 
```

**Comment by andruhon** [comment]
Thank you very much for your feedback! That's weird, but it all works for me.
moment().weekdayCalc({  
  rangeStart: '16 Sept 2015',  
  rangeEnd: '16 Oct 2015',  
  weekdays: [1,2,3,4,5]  
}) 
//this one returns 23
First one works as well. Which version do you use and how did you install it? Could you please also provide error details.

**Comment by adam-lynch** [comment]
Reproduced again on a completely different machine. 

<img width="1025" alt="screen shot 2015-10-17 at 21 28 56" src="https://cloud.githubusercontent.com/assets/1427241/10561115/2d8f2682-7516-11e5-954b-a1e4a4517578.png">

<img width="1049" alt="screen shot 2015-10-17 at 21 30 43" src="https://cloud.githubusercontent.com/assets/1427241/10561119/5b292a66-7516-11e5-96eb-e7c984bfb37f.png">

This time on a Mac, Windows last time.

---

Hmm, just saw the "node standalone" usage bit in the readme now sorry. I don't get it though, it like... half-works?

**Comment by andruhon** [comment]
The problem here, that you trying to use moment-weekday-calculator plugin as a moment library. You should rather do something like that:
```javascript
moment = require('moment');
require('moment-weekday-calc');
console.log(moment().isoWeekdayCalc([2015,0,1],[2015,11,31],[1,2,3,4,5,6,7]));
```
Here you include moment library and after that include moment-weekday-calc which extends moment library with a few weekday calculation functions.

**Comment by adam-lynch** [comment]
Ok thanks. I see you cleaned up the readme a little :+1:. It's especially important the readme makes it really obvious how to use it with node since I discovered this at https://www.npmjs.com/package/moment-weekday-calc :smile:
