### ISSUE TITLE
Variable fed as "exclusions" array becomes blank

### ISSUE THREAD

**Issue by jsh562** [andruhon/moment-weekday-calc#8]
Not 100% sure yet where the problem lies... but

I have a date calculation using `addWeekdaysFromSet` in a `for `loop. It is being fed `workdays`, `weekdays`, `exclusions`, and `inclusions` via variables. 
I set the values for the `workdays`, `weekdays`, `exclusions`, and `inclusions` variables ONCE and do not touch those variables again.

When the code runs and starts the `for `loop, the first calculation goes through fine, but every calculation after the first seems to use a blanked out variable for `exclusions` and does not exclude those days. _I cannot tell if it does the same for `inclusions `because my `inclusions `is an empty array. The other variables are fine._
When I re-set the variable for `exclusions `at the beginning of each `for `loop iteration, every calculation works as expected.

Nowhere else in my code manipulates the variables for the `workdays`, `weekdays`, `exclusions`, and `inclusions`.

**Comment by andruhon** [comment]
So the problem is that Calculator mutates exclusions?

**Comment by jsh562** [comment]
Thats what it looks like to me.

**Comment by andruhon** [comment]
I'll have a look soon.
